# export UID=$(id -u) && export GID=$(id -g) && docker-compose build dotfile && docker-compose run --rm -it dotfile:latest
version: '3'
services:
  dotfile:
    build:
      context: .
      args:
        USER: hori
        UID: $UID
        GID: $GID
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - ~/.ssh:$HOME/.ssh:ro
    working_dir: /mnt/data
