# export CONTAINER_UID=$(id -u) && export CONTAINER_GID=$(id -g) && export CONTAINER_USER=$(whoami) && docker-compose build dotfile && docker compose run --rm  dotfile
version: '3.7'
services:
  dotfile:
    build:
      context: .
      args:
        DockerUSER: ${CONTAINER_USER}
        DockerUID: ${CONTAINER_UID}
        DockerGID: ${CONTAINER_GID}
    network_mode: host  # this parameter is used during run
    tty: true
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - .:${HOME}/mnt/ws
      - ${HOME}/commandhistory.d/docker:${HOME}/commandhistory
      - ${HOME}/.vscode-server:${HOME}/.vscode-server
      - ${HOME}/.ssh:${HOME}/.ssh:ro
      - ${HOME}/.gitconfig:${HOME}/.gitconfig
    working_dir: ${HOME}/mnt/ws
